<?php
require_once('include/database_config.php');
require_once('lib/adodb/adodb.inc.php');
require_once('lib/amp_orm/Data.php');
require_once('lib/amp_orm/Record.php');
require_once('lib/amp_orm/RecordCollection.php');
require_once('lib/amp_orm/AMP_Data_Search.php');
require_once('model/ActiveRecord.php');
require_once('model/Charge.php');
require_once('model/Contact.php');
require_once('model/Invoice.php');
require_once('model/Bandwidth.php');
require_once('model/ProductInstance.php');
require_once('model/SupportContract.php');
require_once('model/Estimate.php');
require_once('model/InvoiceItem.php');
require_once('model/Project.php');
require_once('model/Company.php');
require_once('model/CompanyPreviousBalance.php');
require_once('model/Hour.php');
require_once('model/Payment.php');
require_once('model/Staff.php');

?>
